### ISSUE TITLE
Add support for XML output

### ISSUE THREAD

**Issue by zuBux** [zuBux/drydock#3]
drydock currently supports only JSON output. Adding support for JUnit XML would make output consumable by many CI/CD environments (e.g. Jenkins). Shouldn't be a lot of work, maybe a package such as https://pypi.python.org/pypi/junit-xml can make things easier

**Comment by thanasisk** [comment]
I fixed that, please review PR

**Comment by zuBux** [comment]
Added in https://github.com/zuBux/drydock/commit/478f0782f163779bbba48edd30246866e1615354. Thx!
